{
 "title": "Hedgehog Fabric Platform Stats",
 "description": "This dashboard shows the temperature, voltages, and fanspeeds of the switches in the fabric. https://hedgehog.cloud ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": { "query": "label_values(env)" } },
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "node", "label": "Host Name", "query": { "query": "label_values(hostname)" } }
  ]
 },
 "panels": [
  { "title": "Chip Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Switch ASIC Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fabric_agent_platform_sensor_temperature{env=\"$env\", hostname=\"$node\", name=\"ASIC On-board\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fabric_agent_platform_sensor_temperature{env=\"$env\", hostname=\"$node\", name=\"CPU On-board\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "FRU Temp and RPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Front Fan Air Temp",
   "type": "gauge",
   "description": "Temperature that picked by sensors from different parts of the switch",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fabric_agent_platform_sensor_temperature{hostname=\"$node\", env=\"$env\", name=~\"System Front Left|System Front Middle|System Front Right\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fan Tray Speed",
   "type": "stat",
   "description": "Fan speed located on PSU and trays.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fabric_agent_platform_fan_speed{hostname=\"$node\", env=\"$env\", name=~\"FanTray1-Fan1|FanTray1-Fan2|FanTray2-Fan1|FanTray2-Fan2|FanTray3-Fan1|FanTray3-Fan2|FanTray4-Fan1|FanTray4-Fan2\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "PSU Air Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fabric_agent_platform_sensor_temperature{env=\"$env\", hostname=\"$node\", name=~\"PSU1 Airflow Sensor|PSU2 Airflow Sensor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}