{
 "title": "Switch Critical Resources",
 "description": "Switch ASIC Critical Programmable Resources",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": { "query": "label_values(env)" } },
   { "name": "node", "label": "Switch", "query": { "query": "label_values(hostname)" } },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "IPv4 Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$node Routes Available",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(fabric_agent_critical_resource_ipv4_routes_available{env=\"$env\"} - fabric_agent_critical_resource_ipv4_routes_used{env=\"$env\"}) / fabric_agent_critical_resource_ipv4_routes_available{env=\"$env\"}",
     "legendFormat": "Towards {{hostname}}"
    }
   ]
  },
  {
   "title": "$node Nexthops",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(fabric_agent_critical_resource_ipv4_nexthops_available{env=\"$env\"} - fabric_agent_critical_resource_ipv4_nexthops_used{env=\"$env\"}) / fabric_agent_critical_resource_ipv4_nexthops_available{env=\"$env\"}\n",
     "legendFormat": "Towards {{hostname}}"
    }
   ]
  },
  {
   "title": "$node Neighbors Available",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((fabric_agent_critical_resource_ipv4_neighbors_available{env=\"$env\"} - fabric_agent_critical_resource_ipv4_neighbors_used{env=\"$env\"}) / fabric_agent_critical_resource_ipv4_neighbors_available{env=\"$env\"})",
     "legendFormat": "Towards {{hostname}}"
    }
   ]
  },
  {
   "title": "ACL Resources Available ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node - Groups Available",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((fabric_agent_critical_resource_acl_groups_available{env=\"$env\"} - fabric_agent_critical_resource_acl_groups_used{env=\"$env\"}) / fabric_agent_critical_resource_acl_groups_available{env=\"$env\"}) * 100",
       "legendFormat": "{{direction}}-{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc Critical Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node FDB Entries",
     "type": "gauge",
     "description": "Forwarding Database, Layer 2. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(fabric_agent_critical_resource_fdb_entries_available{env=\"$env\"} - fabric_agent_critical_resource_fdb_entries_used{env=\"$env\"}) / fabric_agent_critical_resource_fdb_entries_available{env=\"$env\"} \n",
       "legendFormat": "Towards {{hostname}}"
      }
     ]
    },
    {
     "title": "$node DNAT Entries",
     "type": "gauge",
     "description": "Destination NAT Hardware resources available",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(fabric_agent_critical_resource_dnat_entries_available{env=\"$env\"} - fabric_agent_critical_resource_dnat_entries_used{env=\"$env\"}) / fabric_agent_critical_resource_dnat_entries_available{env=\"$env\"} ",
       "legendFormat": "Towards {{hostname}}"
      }
     ]
    },
    {
     "title": "$node  Multicast Entries",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 93 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(fabric_agent_critical_resource_ipmc_entries_available{env=\"$env\"} - fabric_agent_critical_resource_ipmc_entries_used{env=\"$env\"}) / fabric_agent_critical_resource_ipmc_entries_available{env=\"$env\"}",
       "legendFormat": "Toward {{hostname}}"
      }
     ]
    }
   ]
  }
 ]
}