name: "commitlint"

on:
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  commitlint:
    runs-on: lab

    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          persist-credentials: "false"

      - name: Block Merge Commits
        if: ${{ always() }}
        uses: Morishiri/block-merge-commits-action@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
